piratedgames/piratedgames/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='inicio'),
    path('juegos/', views.juegos, name='juegos'),
    path('adminselector/', views.adminselector, name='adminselector'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('addgames', views.addgames, name='addgames'),
    path('juego/<slug:slug>/', views.gamepage, name='gamepage'),
    path('logout/', views.logout_view, name='logout'),
    path('users/', views.users, name='users'),
    path('user/<str:username>/', views.see_user, name='user'),
    path('account', views.edit_profile, name='account'),
    path('editgame/<slug:slug>/', views.editgame, name='editgame'),
    path('gamelist/', views.gamelist, name='gamelist'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piratedgames/app/models.py
from django.db import models
from .validators import validate_image_url  # Importar la función de validación personalizada
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser, Group, Permission
from colorfield.fields import ColorField
import markdown

GENERO_CHOICES = [
    ('NULL', 'Género no especificado'),
    ('ACC', 'Acción'),
    ('HOR', 'Horror'),
    ('ADV', 'Aventura'),
    ('RPG', 'RPG'),
    ('SIM', 'Simulador'),
    ('DEP', 'Deportes'),
    ('EST', 'Estrategia'),
    ('PLT', 'Plataformas'),
    ('PZL', 'Puzle'),
    ('CRG', 'Carreras'),
    ('LCH', 'Lucha'),
    ('MSO', 'Musical'),
    ('TIR', 'Tiro'),
    ('OTR', 'Otros'),
    ('FIC', 'Ficción interactiva'),
    ('MMO', 'Multijugador masivo en línea'),
    ('RTS', 'Estrategia en tiempo real'),
    ('TAB', 'Juegos de mesa'),
    ('TRV', 'Trivia'),
    ('VR', 'Realidad virtual'),
]
class Juego(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    imagen = models.URLField(validators=[validate_image_url], blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    genero = models.CharField(
        max_length=4,
        choices=GENERO_CHOICES,
        default='NULL',  # Género por defecto
    )
    slug = models.SlugField(unique=True, blank=True, null=True)  # Campo slug

    def save(self, *args, **kwargs):
        if not self.slug:  # Si no tiene slug, lo genera automáticamente
            self.slug = slugify(self.titulo)
        super().save(*args, **kwargs)

    def descripcion_html(self):
        """Convierte la descripción en Markdown a HTML"""
        return markdown.markdown(self.descripcion)
    
    def __str__(self):
        return self.titulo  
    
class CustomUser(AbstractUser):
    descripcion = models.TextField(blank=True, null=True)
    groups = models.ManyToManyField(Group, related_name='customuser_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_permissions')
    color = ColorField(default='#313131', format='hex')
    def __str__(self):
        return self.username

piratedgames/app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Juego
from django.contrib.auth.models import User, Group, Permission
from .models import CustomUser
from colorfield.forms import ColorField

class RegisterForm(UserCreationForm):
    username = forms.CharField(
        label="Usuario", 
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        label="Correo Electrónico", 
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(
        label="Contraseña", 
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="Confirmar Contraseña", 
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(label="Usuario", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class JuegoForm(forms.ModelForm):
    class Meta:
        model = Juego
        fields = ['titulo', 'descripcion', 'imagen', 'url', 'genero']  # No incluimos el campo 'slug'
        widgets = {
            'descripcion': forms.Textarea(attrs={
                'placeholder': 'Escribe una descripción... (puedes usar Markdown)',
                'class': 'form-control',
                'rows': 5
            }),
            'genero': forms.Select(attrs={'class': 'form-control'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'imagen': forms.URLInput(attrs={'class': 'form-control'}),
            'url': forms.URLInput(attrs={'class': 'form-control'}),
        }

class UserEditForm(forms.ModelForm):
    descripcion = forms.CharField(
        label="Descripción",
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )
    color = ColorField(
        label="Color de perfil",
        required=False,
        widget=forms.TextInput(attrs={'type': 'color', 'class': 'form-control'})
    )

    class Meta:
        model = CustomUser
        fields = ['descripcion', 'color']

piratedgames/app/templates/account.html
{% extends "base.html" %}
{%block navcolor%}{{color}}{%endblock%}
{% block content %}

<!--USUARIO Y FECHA DE CREACION-->
<div class="container mt-5">
    <h2 class="mb-4">{{ request.user.username }}</h2>
    <h5>Fecha de creación: {{ request.user.date_joined|date:"d/m/Y" }}</h5>
</div>
<!--DESCRIPCION-->
    <div class="container mt-5">
        <div class="card p-4" style="background-color: {{color}}; border-color: {{darker_color}};">
            <h3 class="mb-3">Descripción </h3>
            {% if user.descripcion %}
                <p>{{ user.descripcion }}</p>
            {% else %}
                <p>El usuario no tiene descripción.</p>
            {% endif %}
        </div>
            
    </div>
</div>
<!--FORMULARIO PARA CAMBIAR DESCRIPCION Y COLOR-->
<div class="container mt-5">
    <div class="card p-4" style="background-color: {{color}}; border-color: {{darker_color}};">
        <h5>Cambiar descripción 👇(esto solo lo ves vos, los demás usuarios que vean tu cuenta no van a ver este cuadro.)</h5>
        <form method="post">
            {% csrf_token %}
            {{ form.descripcion }}
            <br>
            <button type="submit" class="btn btn-success">Guardar cambios</button>
        </form>
    </div>
    <div class="container mt-5">
        <center>
            <div class="card p-4" style="background-color: {{color}}; border-color: {{darker_color}};">
                <h5>Cambiar color</h5>
                <br><br>
                <form method="post">
                    {% csrf_token %}
                        <div class="color-input">
                        {{ form.color }}
                        </div>
                    <br>
                    <button type="submit" class="btn btn-success">Guardar cambios</button>
                </form>
            </div>
        </center>
<br>
<!--BOTON PARA CERRAR SESION-->
<center >
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Cerrar Sesión</button>
    </form>
</center>
<br>
{% endblock %}

piratedgames/app/templates/addgames.html
{% extends 'base.html' %}
{%block navcolor%}{{color}}{%endblock%}
{% block content %}
<div class="container mt-5">
    <h2>Agregar un Juego</h2>
    <form method="POST" enctype="multipart/form-data" class="addgame-form" style="background-color: {{color}}; border: {{color}}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_titulo" class="form-label">Título del Juego</label>
            {{ form.titulo }}
        </div>

        <div class="mb-3">
          <label for="id_descripcion" class="form-label">Descripción</label>
          <textarea name="descripcion" id="descripcion" placeholder="Escribe una descripción... (puedes usar Markdown)"></textarea>
        </div>

        <div class="mb-3">
            <label for="id_imagen" class="form-label">Imagen (URL)</label>
            {{ form.imagen }}
        </div>

        <div class="mb-3">
            <label for="id_url" class="form-label">Enlace</label>
            {{ form.url }}
        </div>

        <div class="mb-3">
            <label for="id_genero" class="form-label">Género</label>
            {{ form.genero }}
        </div>

        <button type="submit" class="btn btn-primary">Guardar Juego</button>
        <button type="submit" name="agregar_otro" class="btn btn-secondary">Agregar otro juego</button>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelModal">Cancelar</button>
    </form>
</div>

<!-- Modal de Confirmación -->
<div class="modal fade modal-agregar-juego" id="cancelModal" tabindex="-1" aria-labelledby="cancelModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cancelModalLabel">¿Estás seguro?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Si cancelas, los datos no se guardarán.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
        <a href="{% url 'inicio' %}" class="btn btn-success">Cancelar y regresar</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<script>
  var simplemde = new SimpleMDE({ 
      element: document.getElementById("descripcion"),
      spellChecker: false,
      forceSync: true,  // Asegura que el contenido se guarde en el campo textarea original
      autosave: {
          enabled: true,
          unique_id: "game_description"
      }
  });
</script>

piratedgames/app/templates/adminselector.html
{%extends "base.html"%}
{%block navcolor%}{{color}}{%endblock%}
{%block content%}
<br><br><br><br><br>
<div class="container">
    <div class="row">
        <div class="col">
           <center> <a href="{%url 'gamelist'%}" class="btn btn-danger btn-lg btn-block" style="background-color: {{color}}; border: {{color}}">Administrar Juegos</a></center>
        </div>
        <div class="col">
            <center><a href="{%url 'admin:index'%}" class="btn btn-danger btn-lg btn-block" style="background-color: {{color}}; border: {{color}}">Administrar Django</a></center>
        </div>
    </div>
<br>
<center>
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-lg btn-block" style="background-color: {{color}}; border: {{color}}">Cerrar Sesión</button>
    </form>
</center>
{%endblock%}

piratedgames/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Neptune's Pirated Games</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik+Dirt&display=swap" rel="stylesheet">
    <link rel="stylesheet" href='{% static "styles.css" %}'>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybWy6xFiWZKjQ2qnvA1RBO2bsT3b+z8Em2Q3w7Kj1gAdFpm5V" crossorigin="anonymous"></script>
    <script src={% static "jscolor.js" %}></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script src="{% static 'scripts.js' %}"></script>
    <style>
        .card {
            background-color: {% if user.is_authenticated %}{% block cardcolor %}{% endblock %}{% else %}#6E1F1B{% endif %}; /* Fondo rojo oscuro */
            color: white; /* Texto blanco */
            border-radius: 15px; /* Bordes redondeados */
            border: 5px solid {% if user.is_authenticated %}{% block carddarkercolor %}{% endblock %}{% else %}#561d1b{% endif %}; /* Borde más visible pero no grueso */
            transition: transform 0.2s, box-shadow 0.2s; /* Animación suave */
            overflow: hidden; /* Asegura que las imágenes se recorten */
            padding: 10px; /* Espaciado interno */
        }

        .card:hover {
            transform: scale(1.01); /* Aumenta ligeramente el tamaño */
            box-shadow: 0 8px 15px rgba(0, 0, 0, 0.3); /* Sombra más intensa */
            border: 2px solid {% if user.is_authenticated %}{% block cardhoverdarkercolor %}{% endblock %}{% else %}#561d1b{% endif %}; /* Cambia el color del borde al pasar el mouse */
        }
    </style>
    
</head>

<body>
    <!-- base.html -->
<nav class="navbar navbar-expand-sm" style="background-color: {% if user.is_authenticated %}{% block navcolor %}{% endblock %}{% else %}#6E1F1B{% endif %};">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'inicio' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'juegos' %}">Juegos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users' %}">Usuarios</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {%if request.user.is_authenticated%}
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'account'%}">Cuenta</a>
                        </li>
                    {%else%}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                        </li>
                    {%endif%}
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'adminselector'%}">Admin</a>
                        </li>
                    {%endif%}
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#sobreNosotrosModal">Sobre Neptuno</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Modal sobre Neptuno -->
    <div class="modal fade" id="sobreNosotrosModal" tabindex="-1" aria-labelledby="sobreNosotrosLabel" aria-hidden="true" >
        <div class="modal-dialog">
            <div class="modal-content modalinfo">
                <div class="modal-header">
                    <h5 class="modal-title" id="sobreNosotrosLabel">Sobre Nep</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <p>Tenia ganas de hacer una pagina de juegos piratas y bueno acá está</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <br>
    {%block content%} {%endblock%}
</body>
</html>

piratedgames/app/templates/editgame.html
{%extends 'base.html'%}
{%block navcolor%}{{color}}{%endblock%}
{% block content %}
<div class="container mt-5">
    <center><h2>Editar {{juego.titulo}}</h2></center>
    <br>
    <form method="POST" enctype="multipart/form-data" class="addgame-form" style="background-color: {{color}}; border: {{darker_color}}">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="form-label">Editar titulo:</label>
            {{ form.titulo }}
        </div>
        <hr>
        <div class="mb-3">
            <label class="form-label">Descripción actual (markdown aplicado):</label>
            <p>{{ juego.descripcion_html|safe }}</p>
            <hr>
            <label for="id_descripcion" class="form-label">Editar descripción:</label>
            {{ form.descripcion }}
            </div>
        <hr>
        <div class="mb-3">
            <label class="form-label">Imagen actual:</label>
            <img src="{{ juego.imagen }}" class="img-fluid" alt="{{ juego.titulo }} - imagen" style="border-radius: 15px">
            <br><br>
            <label for="id_imagen" class="form-label">Nueva imagen (URL):</label>
            {{ form.imagen }}
        </div>
        <hr>
        <div class="mb-3">
            <label class="form-label">Enlace actual:</label>
            <p>{{ juego.url }}</p>
            <label for="id_url" class="form-label">Editar enlace:</label>
            {{ form.url }}
        </div>
        <hr>
        <div class="mb-3">
            <label class="form-label">Género actual:</label>
            <p>
                {% if juego.genero == 'NULL' %}
                    Género no especificado
                {% elif juego.genero == 'ACC' %}
                    Acción
                {% elif juego.genero == 'HOR' %}
                    Horror
                {% elif juego.genero == 'ADV' %}
                    Aventura
                {% elif juego.genero == 'RPG' %}
                    RPG
                {% elif juego.genero == 'SIM' %}
                    Simulador
                {% elif juego.genero == 'DEP' %}
                    Deportes
                {% elif juego.genero == 'EST' %}
                    Estrategia
                {% elif juego.genero == 'PLT' %}
                    Plataformas
                {% elif juego.genero == 'PZL' %}
                    Puzle
                {% elif juego.genero == 'CRG' %}
                    Carreras
                {% elif juego.genero == 'LCH' %}
                    Lucha
                {% elif juego.genero == 'MSO' %}
                    Musical
                {% elif juego.genero == 'TIR' %}
                    Tiro
                {% elif juego.genero == 'OTR' %}
                    Otros
                {% elif juego.genero == 'FIC' %}
                    Ficción interactiva
                {% elif juego.genero == 'MMO' %}
                    Multijugador masivo en línea
                {% elif juego.genero == 'RTS' %}
                    Estrategia en tiempo real
                {% elif juego.genero == 'TAB' %}
                    Juegos de mesa
                {% elif juego.genero == 'TRV' %}
                    Trivia
                {% elif juego.genero == 'VR' %}
                    Realidad virtual
                {% else %}
                    Género desconocido
                {% endif %}
            </p>
            <label for="id_genero" class="form-label">Editar género:</label>
            {{ form.genero }}
        </div>
        <hr>
        <button type="submit" class="btn btn-primary">Guardar Juego</button>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelModal">Cancelar</button>
    </form>
    <br>
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="delete" value="true">
        <center><button type="submit" class="btn btn-secondary">Eliminar Juego</button></center>
    </form>
</div>
<br>

<!-- Modal de Confirmación -->
<div class="modal fade modal-agregar-juego" id="cancelModal" tabindex="-1" aria-labelledby="cancelModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cancelModalLabel">¿Estás seguro?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Si cancelas, los datos no se guardarán.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
        <a href="{% url 'inicio' %}" class="btn btn-success">Cancelar y regresar</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<script>
  var simplemde = new SimpleMDE({ 
      element: document.getElementById("descripcion"),
      spellChecker: false,
      forceSync: true,  // Asegura que el contenido se guarde en el campo textarea original
      autosave: {
          enabled: true,
          unique_id: "game_description"
      }
  });
</script>

piratedgames/app/templates/gamelist.html
{%extends 'base.html'%}
{%block navcolor%}{{color}}{%endblock%}
{% block content %}
{% for juego in juegos %}
        <div class="col">
        <a href="{% url 'editgame' slug=juego.slug %}" class="text-decoration-none">
            <center>
                <div class="card" style="max-width: 18rem; background-color: {{color}}; border: {{color}}">
                    <div class="card-body">
                        <h5 class="card-title">{{ juego.titulo }}</h5>
                    </div>
                </div>
            </center>
        </a>
    </div>
    <br>
    {% endfor %}
    <div class="col">
        <a href="{% url 'addgames' %}" class="text-decoration-none">
            <center>
                <div class="card" style="max-width: 18rem; background-color: {{color}}; border: {{color}}">
                    <div class="card-body">
                        <h5 class="card-title">Agregar otro juego</h5>
                    </div>
                </div>
            </center>
        </a>
    </div>
{%endblock%}

piratedgames/app/templates/gamepage.html
{%extends "base.html"%}
{%block navcolor%}{{color}}{%endblock%}
{%block content%}
<h1 class="display-3 text-center" style="color: #D1D1D1">{{ juego.titulo }}</h1>
<br>
<center><img src="{% if juego.imagen %}{{ juego.imagen }}{% else %}img-placeholder-dark.jpg{% endif %}" class="img-fluid" alt="{{ juego.titulo }} - imagen" style="border-radius: 15px"></center>
<br>
<div class="container-fluid mt-5 border rounded" style="color: #D1D1D1; max-width: 800px">
    <h3>Descripción</h3>
    <p>{{ juego.descripcion_html|safe }}</p>
</div>
<br>
<div class="container-fluid mt-5 border rounded" style="color: #D1D1D1; max-width: 800px">
    <h3>Descargar</h3>
    <p>{{ juego.url }}</p>
</div>
{%endblock%}

piratedgames/app/templates/inicio.html
{%extends 'base.html'%}
{%block navcolor%}{{color}}{%endblock%}
{%block content%}
<h1 class="display-4 text-center rubik-dirt-regular" style="color: #D1D1D1"><u>Neptune's Pirated Games List</u></h1>
    <hr>
<h1 style="text-align: center;">Inicio</h1>
{%endblock%}

piratedgames/app/templates/juegos.html
{% extends "base.html" %}
{%block navcolor%}{{color}}{%endblock%}
{%block cardcolor%}{{color}}{%endblock%}
{%block carddarkercolor%}{{color}}{%endblock%}
{%block cardhoverdarkercolor%}{{color}}{%endblock%}
{%block content%}
<h1 class="display-4 text-center rubik-dirt-regular" style="color: #D1D1D1"><u>Neptune's Pirated Games List</u></h1>
    <hr>
<div class="container mb-5">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for juego in juegos %}
        <div class="col">
        <a href="{% url 'gamepage' slug=juego.slug %}" class="text-decoration-none">
            <div class="card h-100 shadow-sm">
                <img src="{% if juego.imagen %}{{ juego.imagen }}{% else %}img-placeholder-dark.jpg{% endif %}" class="card-img-top" alt="{{ juego.titulo }} - imagen">
                <div class="card-body">
                    <h5 class="card-title">{{ juego.titulo }}</h5>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{%endblock%}

piratedgames/app/templates/login.html
{% extends 'base.html' %}
{%block navcolor%}{{color}}{%endblock%}
{% block content %}
<div class="container mt-5">
    <center><h2 class="mb-4">Iniciar Sesión</h2></center>
    <form method="post" class="login-form">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="mb-3">
            {{ form.password.label_tag }}
            {{ form.password }}
        </div>
        <button type="submit" class="btn btn-danger">Ingresar</button>
    </form>
</div>
{% endblock %}

piratedgames/app/templates/register.html
{%extends 'base.html'%}
{%block navcolor%}{{color}}{%endblock%}
{%block content%}
<div class="container mt-5">
    <center><h2 class="mb-4">Registrarse</h2></center>
    <form method="post" class="login-form">
        {% csrf_token %}
        
        <div class="mb-3">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>

        <div class="mb-3">
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>

        <div class="mb-3">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
        </div>

        <button type="submit" class="btn btn-danger">Registrarse</button>
    </form>
</div>

{%endblock%}

piratedgames/app/templates/user.html
{%extends 'base.html'%}
{%block navcolor%}{%if user.is_authenticated%}{{color}} {%else%} #6E1F1B {%endif%} {%endblock%}
{%block content%}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4" style="background-color: {{ user.color }}; border: {{ darker_color }};">
            <h1>{{user.username}}</h1>
            <h4>{{user.date_joined}}</h4>
            </div>  
        </div>
        <div class="col-md-12">
            <div class="card mb-4" style="background-color: {{ user.color }}; border: {{ darker_color }};">
            <h2>Descripción</h2>
            <p> {% if user.descripcion %}
                {{ user.descripcion }}
                {% else %}
                    Este usuario no tiene ninguna descripción.
                {% endif %}</p>
            </div>  
        </div>
    </div>
</div>
{%endblock%} 

piratedgames/app/templates/users.html
{% extends 'base.html' %}
{%block navcolor%}{{color}}{%endblock%}
{% block content %}
<div class="container mt-4">
    <div class="row">
        {% for user in users %}
        <div class="col-md-4">
            <a href="{% url 'user' username=user.username %}" class="text-decoration-none">
                <div class="card mb-4" style="background-color: {{ user.color }}; border: {{ user.darker_color }};">
                    <div class="card-header">
                        <h2 class="h5">{{ user.username }}</h2>
                    </div>
                    <div class="card-body">
                        <p>
                            {% if user.descripcion %}
                                {{ user.descripcion }}
                            {% else %}
                                <center>Este usuario no tiene ninguna descripción.</center>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}